# Generated by Django 3.2.5 on 2021-07-29 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Not defined1', max_length=255)),
                ('period', models.CharField(default='Unknown', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(default=None)),
                ('task_type_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='task_types', to='meme_schedules.tasktype')),
            ],
        ),
    ]
