# Generated by Django 3.2.5 on 2021-07-29 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme_schedules', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduletask',
            old_name='task_type_id',
            new_name='task_type',
        ),
    ]
