# Generated by Django 3.2.5 on 2021-07-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_schedules', '0002_rename_task_type_id_scheduletask_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletask',
            name='chat_id',
            field=models.BigIntegerField(default=None),
        ),
    ]
