# Generated by Django 3.2.5 on 2021-07-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_schedules', '0003_alter_scheduletask_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktype',
            name='name',
            field=models.CharField(default='Not defined', max_length=255),
        ),
    ]
